#!/bin/bash
# Sets up a virtual env for the python code

PACKAGE_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")/../" ; pwd -P )"
ENV_DIR=".venv"
SETUP_CMD="develop"
PROMPT_NAME="(codejam-python)"

cd -- "${PACKAGE_DIR}"

# check if virtualenv is installed
if ! hash virtualenv 2>/dev/null; then
    echo "Virtualenv is not installed!"
    exit 1
fi

# check if there is a valid python project
if [ ! -f "${PACKAGE_DIR}/setup.py" ]; then
    echo "The directory ${PACKAGE_DIR} doesn't appear to contain a Python project!"
    exit 1
fi

# Remove existing virtualenv
if [ -d "${ENV_DIR}" ]; then
    rm -r -- "${ENV_DIR}"
fi

# setup the virtualenv and install the package
set -e
virtualenv --prompt="${PROMPT_NAME}" "${ENV_DIR}"
source "${ENV_DIR}/bin/activate"
# install pylint and pep8 in venv
pip install pep8 pylint nose
python setup.py "${SETUP_CMD}"
